baseURL = "https://peterholding.com/"
languageCode = "en-us"
title = "Peter Holding Blog"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "Peter Holding"
  description = "Blog chia sẻ về AI và Expert Advisor."
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
  [[menu.main]]
    name = "AI"
    url = "/tags/ai/"
  [[menu.main]]
    name = "Trading AI"
    url = "/tags/trading/"
  [[menu.main]]
    name = "LTVM"
    url = "/tags/ltvm/"
  [[menu.main]]
    name = "EA Projects"
    url = "/tags/ea/"

[markup.goldmark.renderer]
  unsafe = true
